HELLO = 1
HELLO_OK = 2
AUTH_CHALLENGE = 3
AUTH_RESPONSE = 4
AUTH_OK = 5
OPEN = 6
OPEN_OK = 7
DATA = 8
CLOSE = 9
PING = 10
PONG = 11
REKEY_INIT = 12
REKEY_RESP = 13
REKEY_ACK = 14

MAGIC = b"VN"
VERSION = 1

HEADER_FORMAT = "!2sBBI"

MIN_DATA_FRAME_SIZE = 1024
MAX_FRAME_PAYLOAD_SIZE = 16 * 1024
ENCRYPTED_FRAME_OVERHEAD = 8 + 16
MAX_FRAME_SIZE = MAX_FRAME_PAYLOAD_SIZE + ENCRYPTED_FRAME_OVERHEAD

# Rekeying
REKEY_INTERVAL_PACKETS = 100_000
REKEY_INTERVAL_SECONDS = 600
REKEY_TIMEOUT_SECONDS = 10

# Keepalive
KEEPALIVE_INTERVAL_SECONDS = 30
KEEPALIVE_TIMEOUT_SECONDS = 90

# Padding
MAX_PADDING_SIZE = 255
